apiVersion: v1
kind: Service
metadata:
  name: coreservice
  labels:
    app: coreservice
spec:
  ports:
    - protocol: TCP
      port: 4046
      name: coreweb
  clusterIP: None
  selector:
    app: coreweb