apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web7
spec:
  serviceName: sev7
  replicas: 2
  selector:
    matchLabels:
      app: web7
  template:
    metadata:
      labels:
        app: web7
    spec:
      containers:
        - name: web7
          image: axzxs2001/k8saspnetcoredemo007:v1
          ports:
            - containerPort: 4049
              name: web7
          volumeMounts:
            - name: web7
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: web7
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: "local-storage7"
        resources:
          requests:
            storage: 1Gi
