apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8shealthcheckdemo
spec:
  selector:
    matchLabels:
      app: k8shealthcheckdemo
  replicas: 3
  template:
    metadata:
      labels:
        app: k8shealthcheckdemo
    spec:
      containers:
      - name: k8shealthcheckdemo
        image: gsw/k8shealthcheckdemo:v1.0.0
        imagePullPolicy: IfNotPresent #从本地镜像里拉取
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /readiness
            port: 5000
            #host: 127.0.0.1
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /liveness
            port: 5000
            #host: 127.0.0.1
          initialDelaySeconds: 15
          periodSeconds: 20