apiVersion: v1
kind: Service
metadata:
  name: sev2
  labels:
    app: service2
spec:
  type: NodePort
  selector:
    app: k8saspnetcoredemo002
  ports:
    - protocol: TCP
      nodePort: 30004
      port: 4044
      targetPort: 4044