apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web4
spec:
  serviceName: sev4
  replicas: 2
  selector:
    matchLabels:
      app: web4
  template:
    metadata:
      labels:
        app: web4
    spec:
      containers:
        - name: web4
          image: axzxs2001/k8saspnetcoredemo004:v3
          ports:
            - containerPort: 4047
              name: web4
          volumeMounts:
            - name: web4
              mountPath: /data
      volumes:
        - name: web4
          persistentVolumeClaim:
            claimName: task-pv-claim
