apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web5
spec:
  serviceName: sev5
  replicas: 2
  selector:
    matchLabels:
      app: web5
  template:
    metadata:
      labels:
        app: web5
    spec:
      containers:
        - name: web5
          image: axzxs2001/k8saspnetcoredemo005:v1
          ports:
            - containerPort: 4048
              name: web5
          volumeMounts:
            - name: web5
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: web5
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: "kube-sc"
        resources:
          requests:
            storage: 1Gi
